language: node_js
node_js:
  - 0.10

before_script: 
- npm install
- wget https://codeload.github.com/n1k0/casperjs/legacy.tar.gz/master -nv -O - | tar zx
- sudo ln -s `pwd`/`ls */bin/casperjs` /usr/local/bin/casperjs
- phantomjs --version
- casperjs --version

script: npm test

